name = "silly-site-worker"
main = "workers/index.js"
compatibility_date = "2025-01-01"
account_id = "d82a8a8eb7c815f16d6fcb5a58f12fd3"

# Modern Assets configuration)
[assets]
directory = "./public"   # Point this to your folder of static files
not_found_handling = "404-page"

[env.production]
name = "silly-site-worker-prod"

[env.staging]
name = "silly-site-worker-staging"

[[routes]]
pattern = "silly-site.me/*"
zone_id = "73fbb56d9b1a45c74519f9abec41fd84"

[[routes]]
pattern = "www.silly-site.me/*"
zone_id = "73fbb56d9b1a45c74519f9abec41fd84"

#logs
[observability]
[observability.logs]
enabled = true
invocation_logs = true
